#!/usr/bin/env bash
# shellcheck disable=SC1090
set -o errexit
set -o nounset
set -o pipefail
[[ -n "${XTRACE:+x}" ]] && set -o xtrace
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false
[[ $- =~ [x] ]] && PS4='+[${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]:+${FUNCNAME[0]}}()]: '

readonly file=${1:-}

if [[ -z "$file" ]]; then
  cat >&2 <<EOF
Usage: $0 <file>

Description: Build a docker image

<file>: "42" or "hello-world"
EOF
  exit 1
fi

docker build -t adoyle/minimal:"$file" --build-arg SRC="$file" .
